### ISSUE TITLE
add testing for the keys

### ISSUE THREAD

**Issue by joshuacox** [transmute-industries/pubs#7]
this can be checked with the same command that was used earlier to 

```
ssh-keygen -l -f key
```

**Comment by OR13** [comment]
@joshuacox is this done? 

Seems like we are doing that here.

https://github.com/transmute-industries/pubs/blob/master/.ci/testpub.sh

**Comment by OR13** [comment]
closing this was implemented

**Comment by joshuacox** [comment]
yes this is done
